rake-compiler/rake-compiler

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
Resolves #98. Note that this code duplicates a block of code in `define_compile_tasks`. I could split it out to a private separate method.
> Add rake tasks for files added to spec.files by a cross_compile block

- README.rdoc
I had the syntax slightly wrong and opened up #104. About a minute later I found my mistake. Here is a documentation update would have helped me understand how to use the new feature from #74.
Edit: also added an example of adding files to the gem package.
Sidenote: the docs seem pretty adamant about **i386**-mingw32, but I've been using **x86**-mingw32. Am I wrong, or are the docs out of date, or are the two variants synonyms?
> Describe multiple cross platform options in the README

- .gitignore
* Remove patterns belonging to global git ignore config;
* Specify full paths where possible;
* Mark directories as such with a trailing slash.
Would you be interested by such a change? I think it's better for
occasional contributors so they wouldn't be surprised by unexpected
behavior caused by an entry existing while they think it can't.
I can update if my change in the present form is incorrect.
> Improve git ignore config

- lib/rake/extensiontask.rb
On my platform (FreeBSD), make program is simply `make`, and is
provided in the base install. However, I have to run
`MAKE=make rake compile` to avoid this kind of error:
cd tmp/amd64-freebsd10/uh/2.2.1
rake aborted!
Couldn't find a suitable `make` tool. Use `MAKE` env to set an alternative.
/.../.gem/ruby/22/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:465:in `make'
/.../.gem/ruby/22/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:155:in `block (2 levels) in define_compile_tasks'
/.../.gem/ruby/22/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:154:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:amd64-freebsd10 => compile:uh:amd64-freebsd10 => copy:uh:amd64-freebsd10:2.2.1 => tmp/amd64-freebsd10/uh/2.2.1/uh.so
(See full trace by running task with --trace) …
> Change make program detection with `make' fallback

- features/step_definitions/cross_compilation.rb
Cucumber test suite includes a "I'm running a POSIX operating system"
step. This change updates the host OS test to support most BSD
platforms, it should work with: FreeBSD, NetBSD, OpenBSD,
DragonFly BSD and maybe others.
Popular ruby projects like listen uses the same kind of regular
expression pattern:
https://github.com/guard/listen/blob/master/Gemfile#L11
> Update cucumber POSIX step for *BSD platforms

- tasks/bin/cross-ruby.rake
The extension libraries of the ruby stdlib are not required to cross build binary gems. They just waste compilation time and disk storage.
The option "--with-ext=" is supported since ruby-1.9.2, but ruby-1.8.7 just ignores this option. I verified that the cross ruby-build and building binary gems succeeds with the following ruby versions:
``` sh
rake-compiler cross-ruby VERSION=1.8.7-p374 HOST=i586-mingw32msvc
rake-compiler cross-ruby VERSION=1.9.3-p550 HOST=i586-mingw32msvc
rake-compiler cross-ruby VERSION=2.0.0-p645 HOST=i686-w64-mingw32
rake-compiler cross-ruby VERSION=2.0.0-p645 HOST=x86_64-w64-mingw32
rake-compiler cross-ruby VERSION=2.1.6 HOST=i686-w64-mingw32
rake-compiler cross-ruby VERSION=2.1.6 HOST=x86_64-w64-mingw32
rake-compiler cross-ruby VERSION=2.2.2 HOST=i686-w64-mingw32 …
```
> Don't build extensions for cross rubies.

- README.rdoc
[Rake-compiler-dev-box](https://github.com/tjschuck/rake-compiler-dev-box) is no longer maintained by it's author. Although there are several forks, each adding changes for a given target project, it is generally more extensive to set up and to integrate. Vagrant images are built on the users computer and are not versioned. Moreover the vagrant images are mutable, so that every build can make persistent changes to the box. In the end this makes each and every rake-compiler-dev-box rather unique.
[Rake-compiler-dock](https://github.com/larskanis/rake-compiler-dock) comes as a gem and solves these issues by using Docker instead of Vagrant. That makes rake-compiler-dock faster and more reliable. It also provides a simple API that let's the user integrate the cross build into the Rakefile of …
> Replace rake-compiler-dev-box in favour of rake-compiler-dock

- lib/rake/extensiontask.rb
The previous fake mechanism worked by hooking onto the "require 'rbconfig'" call. This is problematic because bundler internally requires rbconfig, but doesn't work corretly in a faked environment. It then fails to load gems that are also part of the standard library, like json and rdoc. This results in issues like https://github.com/rake-compiler/rake-compiler-dock/issues/8
The fake mechanism is now changed to hook onto the "require 'mkrb'" call, which is typically part of the extconf file, and it is where the faked platform values are actually needed. That way it is loaded after bundler/setup, so that the library paths are set according to the Gemfile.lock, to the native Linux libraries, before the fake environment is active.
Please note, that the build directory of a given gem needs to …
> Change the fake mechanism to be compatible with bundler.

- lib/rake/baseextensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
As mkmf's create_makefile extracts the basename of the given extension name with directory prefixes, I want to make rake-compiler doing so.
> Use basename of ext name as target filename

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
In addition to #128, the install destination should be fixed to make sure the directory prefixes are preserved.
For example, when the extension name is `foo/bar`, the target shared library `bar.so` will be installed in `lib` directory in the current master branch in spite of it should be in `lib/foo`.
Moreover, I've added some examples for the case with directory prefixes.
> Fix install destination with directory prefixes

- lib/rake/baseextensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
Since I write rake's normal task name in Symbol, I've used Symbol for the argument of `Rake::ExtensionTask.new` until rake-compiler v0.9.7. But rake-compiler v0.9.8 raises an error with such case in https://github.com/rake-compiler/rake-compiler/blob/v0.9.8/lib/rake/extensiontask.rb#L115.
I propose to accept Symbol for `Rake::ExtensionTask`'s name like `Rake::Task` https://github.com/ruby/rake/blob/v11.1.2/lib/rake/task.rb#L95.
> Accept symbol name in extension task

- README.rdoc
The single `.` here matches anything. The regular expression was happily working but it's technically not what we want to do. We want to match an actual dot, not "any character".
> Fixing regular expression.

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
While we can write CRuby's extension in C++, `rake compile` does not hook `make` by `*.cc` file changes. When I develop C++ extension, I want to compile it incrementally by `rake compile`. 
So I changed rake-compiler to regard `*.cc` (and `*.cpp` for some users) as `source_files`.
> Regard C++ sources as source_files

- lib/rake/javaextensiontask.rb
Source & Target version 5 are no longer supported for java8 and later. refer https://github.com/ruby-concurrency/concurrent-ruby/issues/747#issuecomment-416230078
> Update source & target version defaults to 6

- lib/rake/javaextensiontask.rb
`classpath` is not set above java 9. `jruby.jar` is found in `<jruby-home>/lib/` directory and that path can be retrieved from `RbConfig::Config['libdir']` without `JRUBY_HOME` set.
Reference: https://github.com/jruby/activerecord-jdbc-adapter/commit/995be701d58f58a34bc0d1448c9cd54f9fcd9e48
> Use 'libdir' of rbconfig to get jruby classpath

- lib/rake/javaextensiontask.rb
Using `libdir` provided by `RbConfig` to compile java extension from MRI
breaks as it can't find `jruby.jar` under `lib` directory. Added a check
on file existence if the path is taken from RbConfig and if it doesn't
exist, check for the path which is set in environment JRUBY_HOME to find
correct `jruby.jar`.
Raise the error to abort compilation if `jruby.jar` is not found.
> Fix cross-platform compilation for Java extensions

- rake-compiler.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement.
> Gemspec: Drop EOL'd rubyforge_project directive

- lib/rake/javaextensiontask.rb
Add the possibility to specify the -encoding argument do javac command.
This is useful for when you have multiple projects to compile and each one have different encodings on class files.
I know that we can set the JAVA_TOOL_OPTIONS env variable like this `ENV['JAVA_TOOL_OPTIONS'] = '-Dfile.encoding=windows-1252'` but if we do this it's gone affect all the JavaExtensionTask that we have defined to run.
> Add the -encoding argument optionally to java compiler

- README.md
- rake-compiler.gemspec
This PR exhaustively lists all supported configuration options in the README. In order to specify this in a formatted table, I unfortunately had to convert from README.rdoc (no table support) to README.md.
The README was converted from RDoc format to Markdown [using RDoc::Markup::ToMarkdown](https://gist.github.com/teeparham/8a99e308884e1c32735a), with a few minor touch-ups along the way to make sure that original formatting was preserved.
> [DOC] Document all configuration options

- History.txt
- lib/rake/javaextensiontask.rb
- spec/lib/rake/javaextensiontask_spec.rb
This rebases/revives PR #118 by Hiroshi Hatake to allow a custom -Xlint:____ option to be specified for JRuby native extensions.  This is particularly important for those who want to:
* Highlight major deprecations with `-Xlint:deprecation`.
* Silence all linting warnings with `-Xlint:unchecked`.
Note that provided no customized linting option, this PR proposes that `-Xlint` be included by default.  This tells the javac compiler to output all _recommended_ warnings.
Additionally, this PR exhaustively lists in the README ALL supported configuration options.  In order to specify this in a formatted table, I had to convert README.rdoc to README.md.
> Make lint options customizable

- lib/rake/extensioncompiler.rb
The previous pattern only recognized 32 bit compiler versions.
Cross compiler names are usually `i686-w64-mingw32-gcc` and `x86_64-w64-mingw32-gcc`.
Background is, that I'll probably split the single  docker image of rake-compiler-dock into target specific versions. And the `x64-mingw32` version currently fails, since it doesn't contain a recognized mingw compiler.
> Extend mingw search pattern to find x86_64 gcc

- tasks/bin/cross-ruby.rake
The .so files of extensions are often manually stripped after compilation per task in a Rakefile. This is done to reduce gem size and because debug information in release binaries isn't particular useful.
This manual step can be avoided, if the cross ruby version is built with stripping enabled. Compatibility is ensured, since stripping files a second time doesn't make a difference.
> Strip cross built shared library files while linking

- lib/rake/extensiontask.rb
lib/rake/extensiontask.rb:471: warning: instance variable @make not initialized
> Fix ruby warning:

- lib/rake/javaextensiontask.rb
rake-compiler defaults to source level and output bytecode version 1.6, corresponding to Java 1.6.
JRuby has not supported 1.6 since the release of JRuby 9.0, five years ago, when we started requiring Java 7.
This PR updates the default versions to "1.7" level for Java 7.
All current supported versions of JRuby require Java 8, but I'm ok with using 1.7 here for any 9.0 stragglers.
> Default to 1.7-level bytecode in Java build

- tasks/bin/cross-ruby.rake
Starting from 3.0.0-preview2, Ruby stopped shipping `tar.bz2` archives. This PR changes the archive format to `tar.gz` for better compatibility.
> Use tar.gz instead of tar.bz2

- tasks/bin/cross-ruby.rake
Rubies can be build like so:
```
rake-compiler cross-ruby VERSION=2.7.0:2.6.0 HOST=x86_64-w64-mingw32:i686-w64-mingw32
```
This builds the cross product of all ":" separated ruby and host versions. To force sequential builds add option "-j1".
This attempt of parallel cross ruby builds doesn't use file locking, but rake `multitask` only. It is an alternative way to #162 .
> Allow building of cross rubies in parallel

- tasks/bin/cross-ruby.rake
This was introduced in commit a7c113e580c1565000166f9967da82ff2ecdaeaa to avoid interference with host build. However it prohibits setting important flags for cross-build.
Also don't force 'LDFLAGS=-pipe -s' in configure, which doesn't work with `clang` compiler targeting MacOS. It can now be set externally.
Fixes #178
> Don't mask out build env vars for cross-ruby

- lib/rake/extensiontask.rb
Iron Ruby was abandoned as a project by Microsoft in spring of 2011.  It only supports Ruby 1.8.6 and I am wondering if rake-compiler will even load on that last release.  Time to remove this warning saying they do not support native c-exts?
> IronRuby has been a dead project for 10 years

- lib/rake/javaextensiontask.rb
This PR avoids a Ruby warning.
Seen at https://travis-ci.org/github/ruby-concurrency/concurrent-ruby/jobs/755324784#L277
> Avoid warning: assigned but unused variable - e

- .github/workflows/test.yml
This PR **adds Ruby 3.0** to the build matrix in CI.
Got to 🟢 !
> CI: Add Ruby 3.0 to the build matrix

- lib/rake/extensiontask.rb
Until now rake-compiler uses `make` to build the extension binary, but doesn't use `make install` to copy it into the `lib` directory. This has the downside, that only the extension binary is copied, but no additional files. In particular files registered per mkmf's `$INSTALLFILES` mechanism are not respected. Using `make install` fixes this and possibly also #189.
With this PR, the call to `make install` is not invoked for cross ruby tasks but only for native compile. This changes the cross build, so that cross compiled extension binaries are no longer copied into the native `lib` directory. IMHO that makes sense in any case, since the cross compiled extension binaries belong into the platform gems only and are superfluous in the native `lib` directory. 
As another extension to this PR, …
> Use "make install" instead of manually copying extension binary

- lib/rake/extensiontask.rb
"rake native gem" without "cross" didn't set the ruby version constraint.
Instead it failed with NoMethodError like so:
```
/ffi $ rake native gem
no configuration section for specified version of Ruby (rbconfig-i386-mingw32-2.6.3)
no configuration section for specified version of Ruby (rbconfig-x64-mingw32-2.6.3)
install -c build/x86_64-linux/ffi_c/2.6.3/ffi_c.so lib/ffi_c.so
cp build/x86_64-linux/ffi_c/2.6.3/ffi_c.so build/x86_64-linux/stage/lib/ffi_c.so
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/home/lars/.rvm/gems/ruby-2.6.3/gems/rake-compiler-1.0.9/lib/rake/extensiontask.rb:515:in `ruby_api_version'
/home/lars/.rvm/gems/ruby-2.6.3/gems/rake-compiler-1.0.9/lib/rake/extensiontask.rb:262:in `block in define_native_tasks' …
```
> Fix determining of ruby versions in "rake native gem"

- lib/rake/extensiontask.rb
- lib/rake/javaextensiontask.rb
The fix in cd9daf3fd02345c303390f533b586376a45f2554 seems not enough since the .so file is still copied to an extra folder in the stage directory.  This file tasks created are also not right.
> Fix other "lib binary paths"

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
The `required_ruby_version` was set twice, although one in `define_native_tasks` is enough.
The original commit that introduced automatic setting of `required_ruby_version` was https://github.com/rake-compiler/rake-compiler/commit/0dc23504cb03ed2fb3c506e1bb58af48d3851d1e . It detected the ruby version entirely based on `RUBY_CC_VERSION`. Later on there was commit https://github.com/rake-compiler/rake-compiler/commit/0dc23504cb03ed2fb3c506e1bb58af48d3851d1e which introduced setting the `required_ruby_version` for native but not cross gems and only for the active ruby versions. This made the first detection obsolete, but it wasn't deleted so far. This is fixed by this PR.
Fixes #198
> Set correct `required_ruby_version` when some `RUBY_CC_VERSION`s are missing

- lib/rake/javaextensiontask.rb
- spec/lib/rake/javaextensiontask_spec.rb
Fixes #200 
The patch can solve the problem https://github.com/msgpack/msgpack-ruby/issues/239
Without this option (see `Method java/nio/ByteBuffer.clear:()Ljava/nio/ByteBuffer;` at 39):
```
$ javap -p -c -s -v -l -constants tmp/java/msgpack/org/msgpack/jruby/Encoder.class
(snip)
private org.jruby.runtime.builtin.IRubyObject readRubyString();
descriptor: ()Lorg/jruby/runtime/builtin/IRubyObject;
flags: (0x0002) ACC_PRIVATE
Code:
stack=8, locals=2, args_size=1
0: aload_0
1: getfield      #15                 // Field runtime:Lorg/jruby/Ruby;
4: new           #89                 // class org/jruby/util/ByteList
7: dup
8: aload_0
9: getfield      #25                 // Field buffer:Ljava/nio/ByteBuffer;
12: invokevirtual #78                 // Method java/nio/ByteBuffer.array:()[B
15: …
```
> Support --release option to build JRuby extension for older platforms

- lib/rake/baseextensiontask.rb
- lib/rake/compiler_config.rb
- lib/rake/extensiontask.rb
- spec/lib/rake/compiler_config_spec.rb
- spec/lib/rake/extensiontask_spec.rb
Since Rubygems 3.3.21, the Gem::Platform name always contains the library version for gnu platforms. So where the rake-compiler config entries previously were:
```yaml
---
rbconfig-x86_64-linux-gnu-2.7.0: "/usr/local/rake-compiler/ruby/x86_64-redhat-linux/ruby-2.7.0/lib/ruby/2.7.0/x86_64-linux-gnu/rbconfig.rb"
rbconfig-x86_64-linux-2.7.0: "/usr/local/rake-compiler/ruby/x86_64-redhat-linux/ruby-2.7.0/lib/ruby/2.7.0/x86_64-linux-gnu/rbconfig.rb"
```
with later versions of rubygems, it is only
```yaml
---
rbconfig-x86_64-linux-gnu-2.7.0: "/usr/local/rake-compiler/ruby/x86_64-redhat-linux/ruby-2.7.0/lib/ruby/2.7.0/x86_64-linux-gnu/rbconfig.rb"
```
This means that the current way of finding a matching runtime, by doing a string comparison on the config keys, is no longer appropriate. This is …
> Add support for RubyGems 3.3.21 or later

- lib/rake/baseextensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
If a build wishes to generate some of the extension source files then the pattern input is insufficient. Provide a place to stash an additional FileList that will then become a dependency of the compile tasks.
Example:
```ruby
file 'ext/libfoo/generated.c' do |t|
open(t.name, 'w+) { |f| f << '#include <foo.h>' }
end
Rake::ExtensionTask.new('foo') do |ext|
ext.extra_sources << 'generated.c'
end
```
> baseextensiontask: provide an API to allow for dynamic sources

- lib/rake/javaextensiontask.rb
this allows using
```
Rake::JavaExtensionTask.new("name", gemspec) do |ext|
ext.release = '8'
end
```
on Java 8 (for building the gem), because the flag is available since Java 9, see https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html
this flag is for backward compatibility, so it's safe to just skip it if we can't use it.
relates to https://github.com/puma/puma/pull/3109 https://github.com/socketry/nio4r/pull/292
> Don't use --release flag on Java 8

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
__Context__
In rake-compiler 1.2.1 and earlier, if an extension did something like this, rake-compiler handled it gracefully:
```ruby
Rake::ExtensionTask.new("gem", spec) do |ext|
ext.config_options << ENV["EXTOPTS"] # this is probably going to be nil
end
```
It is OK to do this because in 1.2.1 and earlier, the command array was executed as:
```
sh cmd.join(' ')
```
However, this was changed in 1.2.2 to
```
sh *cmd
```
which of course is preferable. However, this breaks extensions [like nokogiri that do something silly like above](https://github.com/sparklemotion/nokogiri/actions/runs/5109347425/jobs/9184057367).
__Details__
I've fixed Nokogiri (see https://github.com/sparklemotion/nokogiri/pull/2894) but I do think that there may be other gems impacted by this change.
This PR does a few …
> handle nil in config options (broken in 1.2.2)

- README.md
I think that applying syntax highlighting here will provide a more readable README.
Since syntax highlighting cannot be performed on [indented code blocks](https://spec.commonmark.org/0.30/#indented-code-blocks), I replaced all ruby code parts with [fenced code blocks](https://spec.commonmark.org/0.30/#fenced-code-blocks) and specified `ruby` as their [info strings](https://spec.commonmark.org/0.30/#info-string). If you believe that the mixing of indented code blocks and fenced code blocks should be avoided, then I'm willing to rewrite all ones in fenced code blocks.
> Add syntax-highlighting to example Ruby code in README.md

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
closes: https://github.com/rake-compiler/rake-compiler/issues/202
Instead of creating `.rake-compiler-siteconf.rb` to override `RbConfig::MAKEFILE_CONFIG` and `RbConfig::CONFIG`, set environment variables to `make install` command. Since `RbConfig` is suppose to be readonly, we shouldn't overwrite its values.
Additionally, this update addresses a bug caused by `.rake-compiler-siteconf.rb`. The file's hardcoded destination path causes `rake-compiler` to consistently create files in that location, even if the project is renamed or moved. Consequently, changes to the gem project's path do not trigger the file task to update the file. This fix resolves this issue.
> Use ENV variables to set conf paths

- lib/rake/extensiontask.rb
Pathname#relative_path_from supports string arguments only in Ruby 2.6+ (see https://github.com/ruby/ruby/commit/dde0e30c)
Fixes #224
> Restore Ruby 2.5 support broken in v1.2.4

- lib/rake/extensiontask.rb
> `require` the target `rbconfig` rather than copypasting verbatim

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
Rubygems does not correctly recognize `-musl` or `-gnu` platform suffixes until v3.3.22.
If rake-compiler is building a linux native gem that specifies a libc in its platform object, then add ">= 3.3.22" to the required_rubygems_version requirement.
https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#3322--2022-09-07
While working on musl support in the precompilation toolchain:
- https://github.com/rake-compiler/rake-compiler-dock/pull/111
- https://github.com/flavorjones/ruby-c-extensions-explained/pull/27
- https://github.com/sparklemotion/sqlite3-ruby/pull/442
- https://github.com/sparklemotion/nokogiri/pull/3111
I noticed that Ruby 3.0 is still shipping with Rubygems 3.2.33, which does not recognize these gem platforms. 
Specifying the rubygems requirement changes the error …
> set `required_rubygems_version` for native gems that specify the linux libc

- lib/rake/extensiontask.rb
- spec/lib/rake/extensiontask_spec.rb
If files is retrieved from Git and the task is executed after the files are deleted but before they are committed to Git, an error occurs because the files do not exist.
Getting files from Git is a common pattern because it's default of newgems by generated by Bundler.
https://github.com/rubygems/rubygems/blob/ad394cadc73f2239b907e6cd02a0dfae2ef65999/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt#L31-L35
I would like to avoid an error in this situation, so I fixed not to create rake tasks for compile if files don't exist.
> Don't generate additional rake tasks when files don't exist

- lib/rake/javaextensiontask.rb
Java 21, the minimum Java for upcoming JRuby 10, can only compile Java code to target Java 8 or higher. This causes projects that have not explicitly configured their source_level and target_level to fail building on such recent JDKs.
This patch sets the minimum to Java 8, which is the minimum version for JRuby versions 9.2 and higher (with 9.2 and 9.3 already EOL).
This can be merged and released any time and I believe it is a safe change.
> Default to Java 8 build target at minimum

- tasks/bin/cross-ruby.rake
rake-compiler does not correctly configure a ruby with a double-digit version segment. For example, if I build 2.6.10, the `config.yml` will contain an entry for `2.6.1`.
Previously the regexp used was
(\d.\d.\d.)
Now the regexp is
(\d+\.\d+\.\d+)
> fix: rake task 'update-config' supports double-digit version segments
